#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "Usage: $0 <kernel-source> <clang-r365631c-dir> <aarch64-gcc-4.9-dir> [output-dir] [reproducibility-key.pem]" >&2
}

if [[ $# -lt 3 || $# -gt 5 ]]; then
    usage
    exit 2
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
project_dir="$(cd -- "${script_dir}/.." && pwd)"
kernel_source="$(realpath "$1")"
clang_dir="$(realpath "$2")"
gcc_dir="$(realpath "$3")"
output_dir="${4:-${kernel_source}/out-lowram-r5}"
reproducibility_key="${5:-}"
config_source="${project_dir}/configs/tb-x505l-lowram-r5.config"

if [[ ! -f "${kernel_source}/Makefile" ]]; then
    echo "Kernel Makefile not found in ${kernel_source}" >&2
    exit 1
fi

if [[ ! -x "${clang_dir}/bin/clang" ]]; then
    echo "Clang executable not found in ${clang_dir}/bin" >&2
    exit 1
fi

if [[ ! -x "${gcc_dir}/bin/aarch64-linux-android-gcc" ]]; then
    echo "AArch64 GCC 4.9 toolchain not found in ${gcc_dir}/bin" >&2
    exit 1
fi

if [[ ! -f "${config_source}" ]]; then
    echo "Release config not found: ${config_source}" >&2
    exit 1
fi

if ! grep -q 'tb_x505l_vendor_module' "${kernel_source}/kernel/module.c"; then
    echo "The r5 source patch is not applied to ${kernel_source}" >&2
    exit 1
fi

if [[ -d "${output_dir}" ]] && find "${output_dir}" -mindepth 1 -print -quit | grep -q .; then
    if [[ "${TB_X505L_ALLOW_DIRTY_OUT:-0}" != "1" ]]; then
        echo "Output directory is not empty: ${output_dir}" >&2
        echo "Use a fresh directory, or set TB_X505L_ALLOW_DIRTY_OUT=1 deliberately." >&2
        exit 1
    fi
fi

mkdir -p "${output_dir}"
cp "${config_source}" "${output_dir}/.config"

if [[ -n "${reproducibility_key}" ]]; then
    reproducibility_key="$(realpath "${reproducibility_key}")"
    if [[ ! -f "${reproducibility_key}" ]]; then
        echo "Reproducibility key not found: ${reproducibility_key}" >&2
        exit 1
    fi
    mkdir -p "${output_dir}/certs"
    install -m 0644 "${project_dir}/reproducibility/x509.genkey" "${output_dir}/certs/x509.genkey"
    install -m 0600 "${reproducibility_key}" "${output_dir}/certs/signing_key.pem"
    echo "Using the deliberately public r5 reproducibility key:"
    sha256sum "${output_dir}/certs/signing_key.pem"
fi

echo "Compiler:"
"${clang_dir}/bin/clang" --version | head -n 1
echo "Config SHA-256:"
sha256sum "${output_dir}/.config"

make_args=(
    -C "${kernel_source}"
    O="${output_dir}"
    ARCH=arm64
    SUBARCH=arm64
    LOCALVERSION=+
    HOSTCFLAGS=-fcommon
    CC="${clang_dir}/bin/clang"
    CLANG_TRIPLE=aarch64-linux-gnu-
    CROSS_COMPILE="${gcc_dir}/bin/aarch64-linux-android-"
)

# r5 reused the deterministic empty initramfs generated by an earlier build.
# Its cpio entry timestamp is embedded in Image even though the boot ramdisk is
# empty. Generate that 133-byte input first, then use the final kernel identity.
env \
    KBUILD_BUILD_USER=codex-lowram \
    KBUILD_BUILD_HOST=tb-x505l \
    KBUILD_BUILD_VERSION=5 \
    KBUILD_BUILD_TIMESTAMP='Sun Aug 30 19:02:44 UTC 2026' \
    make "${make_args[@]}" usr/

env \
    KBUILD_BUILD_USER=codex-lowram \
    KBUILD_BUILD_HOST=tb-x505l \
    KBUILD_BUILD_VERSION=5 \
    KBUILD_BUILD_TIMESTAMP='Sun Aug 30 21:18:08 UTC 2026' \
    make "${make_args[@]}" \
    -j"$(nproc)" \
    Image

image_path="${output_dir}/arch/arm64/boot/Image"
if [[ ! -f "${image_path}" ]]; then
    echo "Build completed without the expected Image: ${image_path}" >&2
    exit 1
fi

echo "Built Image:"
ls -l "${image_path}"
sha256sum "${image_path}"
